# Generated by Django 6.0.3 on 2026-04-21 01:59

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("creators", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("concert", "Concert"),
                            ("art_show", "Art Show"),
                            ("market", "Maker Market"),
                            ("festival", "Festival"),
                            ("open_mic", "Open Mic"),
                            ("workshop", "Workshop"),
                            ("other", "Other"),
                        ],
                        default="concert",
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                ("doors_time", models.TimeField(blank=True, null=True)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "ticket_price_cents",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Price in cents (e.g., 1500 = $15.00)",
                        null=True,
                    ),
                ),
                (
                    "ticket_url",
                    models.URLField(blank=True, help_text="External ticket link"),
                ),
                (
                    "poster_image",
                    models.ImageField(blank=True, upload_to="events/posters/"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_virtual", models.BooleanField(default=False)),
                ("stream_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who created this event (for permissions)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizing_creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Creator or collective organizing this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "organizing_venue",
                    models.ForeignKey(
                        blank=True,
                        help_text="Venue organizing this event (can differ from host venue)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_events",
                        to="venues.venueprofile",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="venues.venueprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="BookingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("creator_to_venue", "Creator → Venue"),
                            ("venue_to_creator", "Venue → Creator"),
                        ],
                        help_text="Whether the creator reached out or the venue did",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("concert", "Concert"),
                            ("art_show", "Art Show"),
                            ("market", "Maker Market"),
                            ("festival", "Festival"),
                            ("open_mic", "Open Mic"),
                            ("workshop", "Workshop"),
                            ("other", "Other"),
                        ],
                        default="concert",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_dates",
                    models.TextField(
                        help_text="Preferred dates or date ranges, freeform text"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Introduction, details about the proposed event"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Reply from the receiving party"
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_requests",
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_booking_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_requests",
                        to="venues.venueprofile",
                    ),
                ),
                (
                    "resulting_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="The event created from this booking, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_requests",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "set_description",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Acoustic Set, DJ Set, Live Painting",
                        max_length=255,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_slots",
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="events.event",
                    ),
                ),
                (
                    "venue_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="The area within the venue (e.g., Main Stage, Gallery Room)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_slots",
                        to="venues.venuearea",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="creators",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="events.EventSlot",
                to="creators.creatorprofile",
            ),
        ),
    ]
