# Generated by Django 5.2.14 on 2026-05-14 03:36

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0002_historicalcreatorprofile"),
        ("events", "0001_initial"),
        ("venues", "0002_historicalvenueprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBookingRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("creator_to_venue", "Creator → Venue"),
                            ("venue_to_creator", "Venue → Creator"),
                        ],
                        help_text="Whether the creator reached out or the venue did",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("concert", "Concert"),
                            ("art_show", "Art Show"),
                            ("market", "Maker Market"),
                            ("festival", "Festival"),
                            ("open_mic", "Open Mic"),
                            ("workshop", "Workshop"),
                            ("other", "Other"),
                        ],
                        default="concert",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_dates",
                    models.TextField(
                        help_text="Preferred dates or date ranges, freeform text"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Introduction, details about the proposed event"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Reply from the receiving party"
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resulting_event",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The event created from this booking, if any",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="events.event",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="venues.venueprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical booking request",
                "verbose_name_plural": "historical booking requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
