# Generated by Django 5.2.14 on 2026-07-20 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0003_creatormembership_guest_email_and_more"),
        ("events", "0002_historicalbookingrequest"),
        ("venues", "0002_historicalvenueprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventslot",
            name="guest_name",
            field=models.CharField(
                blank=True,
                help_text="Performer not on the hub (e.g., a touring act)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="eventslot",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_slots",
                to="creators.creatorprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventslot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("creator__isnull", False), ("guest_name", "")),
                    models.Q(
                        ("creator__isnull", True),
                        models.Q(("guest_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="slot_creator_xor_guest",
            ),
        ),
    ]
