# Generated by Django 5.2.14 on 2026-07-20 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_notification_notification_type"),
        ("creators", "0004_creatorprofile_claim_contact_email_and_more"),
        ("events", "0003_eventslot_guest_name_alter_eventslot_creator_and_more"),
        ("venues", "0003_historicalvenueprofile_claim_contact_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text='Where it happens when not at a listed venue (e.g., "Seneca Street, Oil City")',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("cancelled", "Cancelled"),
                    ("postponed", "Postponed"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("venue__isnull", False),
                    models.Q(("location_name", ""), _negated=True),
                    _negated=True,
                ),
                name="event_venue_or_location_not_both",
            ),
        ),
    ]
