# Generated by Django 5.2.14 on 2026-07-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_location_address_event_location_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="previous_location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
