# Generated by Django 6.0.3 on 2026-04-21 01:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "street",
                    models.TextField(blank=True, help_text="Street address / line 1"),
                ),
                (
                    "street_2",
                    models.CharField(
                        blank=True, help_text="Apt, suite, unit, etc.", max_length=255
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="US", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "ordering": ["state", "city"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("creator", "Creator"),
                            ("venue", "Venue"),
                            ("both", "Both"),
                        ],
                        default="both",
                        help_text="Which profile types can use this availability flag",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Shown to users when selecting this availability type",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Availability Type",
                "verbose_name_plural": "Availability Types",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Public name; defaults to email prefix if blank",
                        max_length=255,
                    ),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/")),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City or region", max_length=255
                    ),
                ),
                (
                    "email_digest",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email updates about followed creators and events",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Toggle off to pause without deleting"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "Weekends only", "Booked through June, open July onward"',
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "availability_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_availabilities",
                        to="core.availabilitytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Availability",
                "verbose_name_plural": "Profile Availabilities",
                "ordering": ["availability_type__sort_order"],
            },
        ),
    ]
