# Generated by Django 6.0.3 on 2026-04-21 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("creators", "0001_initial"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profileavailability",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="creators.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="profileavailability",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="venues.venueprofile",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional structured address for location-based features",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="followed_creators",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="creators.creatorprofile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="followed_venues",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="venues.venueprofile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="profileavailability",
            constraint=models.UniqueConstraint(
                condition=models.Q(("creator__isnull", False)),
                fields=("availability_type", "creator"),
                name="unique_availability_per_creator",
            ),
        ),
        migrations.AddConstraint(
            model_name="profileavailability",
            constraint=models.UniqueConstraint(
                condition=models.Q(("venue__isnull", False)),
                fields=("availability_type", "venue"),
                name="unique_availability_per_venue",
            ),
        ),
    ]
