# Generated by Django 5.2.14 on 2026-05-14 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_historicalreport_historicaluserprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreport",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Null for anonymous feedback-form submissions; also null after the reporter deletes their account.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for anonymous feedback-form submissions; also null after the reporter deletes their account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_filed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
