# Generated by Django 6.0.3 on 2026-04-30 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["word"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="Suspended users cannot log in or interact with the platform",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("post", "Community Post"),
                            ("endorsement", "Endorsement"),
                            ("user", "User"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_id",
                    models.CharField(
                        help_text="UUID or identifier of the reported content",
                        max_length=255,
                    ),
                ),
                ("content_url", models.CharField(blank=True, max_length=500)),
                ("reason", models.TextField(help_text="Why is this being reported?")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("action_taken", "Action Taken"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not shown to reporter)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
