# Generated by Django 5.2.14 on 2026-07-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_historicalreport_reporter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("follow", "New Follower"),
                    ("like", "Post Liked"),
                    ("reply", "New Reply"),
                    ("booking", "Booking Update"),
                    ("profile_approved", "Profile Approved"),
                    ("event", "Event Update"),
                ],
                max_length=20,
            ),
        ),
    ]
