# Generated by Django 6.0.3 on 2026-05-04 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_blockedword_userprofile_is_suspended_report"),
        ("creators", "0003_creatorprofile_other_genres_and_more"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_counts",
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_counts",
                        to="venues.venueprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("creator__isnull", False)),
                        fields=("creator", "date"),
                        name="unique_creator_view_per_day",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("venue__isnull", False)),
                        fields=("venue", "date"),
                        name="unique_venue_view_per_day",
                    ),
                ],
            },
        ),
    ]
