# Generated by Django 5.2.14 on 2026-07-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="coordinates_manual",
            field=models.BooleanField(
                default=False,
                help_text="Coordinates placed by hand — auto-geocoding and the clear-on-edit rule both leave them alone.",
            ),
        ),
    ]
