# Generated by Django 5.2.14 on 2026-07-24 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_userprofile_blocked_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("report_filed", "Report filed"),
                            ("removal_requested", "Removal requested"),
                            ("user_blocked", "User blocked"),
                            ("user_unblocked", "User unblocked"),
                            ("profile_suppressed", "Profile suppressed"),
                            ("account_suspended", "Account suspended"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable subject (profile slug, username, content id).",
                        max_length=255,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who took the action; null for anonymous or system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
