# Generated by Django 6.0.3 on 2026-04-21 01:59

import django.db.models.deletion
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price_cents",
                    models.PositiveIntegerField(
                        help_text="Price per unit at time of purchase (snapshot)"
                    ),
                ),
                ("platform_fee_cents", models.PositiveIntegerField(default=0)),
                ("stripe_transfer_id", models.CharField(blank=True, max_length=255)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order__created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("digital_music", "Digital Music"),
                            ("physical_music", "Physical Music"),
                            ("artwork", "Artwork"),
                            ("jewelry", "Jewelry"),
                            ("merch", "Merch"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveIntegerField(
                        help_text="Price in cents (e.g., 1000 = $10.00)"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_digital", models.BooleanField(default=False)),
                ("file", models.FileField(blank=True, upload_to="commerce/downloads/")),
                (
                    "inventory_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for unlimited (digital products)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "shipping_note",
                    models.TextField(
                        blank=True, help_text="Shipping info for physical items"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="commerce/products/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("buyer_email", models.EmailField(max_length=254)),
                (
                    "stripe_checkout_session_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("stripe_payment_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("fulfilled", "Fulfilled"),
                            ("partially_fulfilled", "Partially Fulfilled"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("shipping_address", models.JSONField(blank=True, null=True)),
                ("total_cents", models.PositiveIntegerField(default=0)),
                ("platform_fee_cents", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
