# Generated by Django 6.0.3 on 2026-05-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="creators.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="commerce.order",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="creators.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="commerce.product",
            ),
        ),
        migrations.AddField(
            model_name="productgroup",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_groups",
                to="creators.creatorprofile",
            ),
        ),
        migrations.AddField(
            model_name="productgroupitem",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="commerce.productgroup",
            ),
        ),
        migrations.AddField(
            model_name="productgroupitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="commerce.product",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="commerce.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("creator", "slug"), name="unique_product_slug_per_creator"
            ),
        ),
        migrations.AddConstraint(
            model_name="productgroupitem",
            constraint=models.UniqueConstraint(
                fields=("group", "product"), name="unique_product_per_group"
            ),
        ),
    ]
