# Generated by Django 6.0.3 on 2026-05-02 03:57

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_initial"),
        ("creators", "0003_creatorprofile_other_genres_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[("collection", "Collection"), ("set", "Set")],
                        default="collection",
                        max_length=20,
                    ),
                ),
                (
                    "bundle_price_cents",
                    models.IntegerField(help_text="Price for the entire group"),
                ),
                ("image", models.ImageField(blank=True, upload_to="commerce/groups/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_groups",
                        to="creators.creatorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.productgroup",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="commerce.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "product"), name="unique_product_per_group"
                    )
                ],
            },
        ),
    ]
