# Generated by Django 6.0.3 on 2026-05-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0003_productgroup_productgroupitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Flat-rate shipping cost in cents (0 = free shipping)",
            ),
        ),
    ]
