# Generated by Django 6.0.3 on 2026-05-07 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Oil Region Creative Hub",
                        help_text="Displayed in the page title, footer, and emails.",
                        max_length=120,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short phrase used in social/OG meta tags.",
                        max_length=200,
                    ),
                ),
                (
                    "origin_story",
                    models.TextField(
                        blank=True,
                        help_text="One-paragraph blurb shown in the site footer.",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Address shown to suspended users and in 'contact us' links.",
                        max_length=254,
                    ),
                ),
                (
                    "source_repo_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the source code repository (footer + soft-launch banner).",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default Open Graph / social-share image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site branding",
            },
        ),
    ]
