# Generated by Django 6.0.3 on 2026-05-07 04:14

import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_seed_site_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitebranding",
            name="active_theme",
            field=models.CharField(
                choices=apps.pages.models._theme_choices,
                default="default",
                help_text="Picks a theme directory under ./themes/. Overrides only CSS variables and (optionally) templates — no code runs.",
                max_length=80,
            ),
        ),
    ]
