# Generated by Django 6.0.3 on 2026-04-21 01:59

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VenueProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("website", models.URLField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="profiles/%(class)s/"),
                ),
                (
                    "header_image",
                    models.ImageField(blank=True, upload_to="headers/%(class)s/"),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Draft → Pending Review → Published",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the profile was submitted for review",
                        null=True,
                    ),
                ),
                ("stripe_account_id", models.CharField(blank=True, max_length=255)),
                ("stripe_onboarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("cafe", "Café"),
                            ("gallery", "Gallery"),
                            ("theater", "Theater"),
                            ("outdoor", "Outdoor Space"),
                            ("community_space", "Community Space"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="venue_profiles",
                        to="core.address",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="venues", to="venues.amenity"
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_venue_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The owner/primary manager of this venue",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name="VenueContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("general", "General Inquiries"),
                            ("press", "Press / Media"),
                            ("technical", "Technical / Sound"),
                            ("gallery", "Gallery / Exhibition"),
                            ("events", "Events"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("form", "Contact Form (URL)"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Email address, phone number, or URL depending on method",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Contact person's name (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Show on public venue page. Uncheck for contacts only visible to confirmed performers.",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Best reached after 2pm', 'For shows only, not private events'",
                        max_length=255,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="venues.venueprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "contact_type", "method"],
            },
        ),
        migrations.CreateModel(
            name="VenueSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("bandcamp", "Bandcamp"),
                            ("soundcloud", "SoundCloud"),
                            ("spotify", "Spotify"),
                            ("youtube", "YouTube"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("mastodon", "Mastodon"),
                            ("bluesky", "Bluesky"),
                            ("etsy", "Etsy"),
                            ("threads", "Threads"),
                            ("twitter_x", "X / Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="venues.venueprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="VenueArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="venues.venueprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("venue", "name"), name="unique_area_per_venue"
                    )
                ],
            },
        ),
    ]
