# Generated by Django 5.2.14 on 2026-05-14 03:36

import django.db.models.deletion
import simple_history.models
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_historicalreport_historicaluserprofile"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalVenueProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("slug", models.SlugField(max_length=255)),
                ("website", models.URLField(blank=True)),
                ("profile_image", models.TextField(blank=True, max_length=100)),
                ("header_image", models.TextField(blank=True, max_length=100)),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Draft → Pending Review → Published",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the profile was submitted for review",
                        null=True,
                    ),
                ),
                ("stripe_account_id", models.CharField(blank=True, max_length=255)),
                ("stripe_onboarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "venue_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar"),
                            ("cafe", "Café"),
                            ("gallery", "Gallery"),
                            ("theater", "Theater"),
                            ("outdoor", "Outdoor Space"),
                            ("community_space", "Community Space"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.address",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The owner/primary manager of this venue",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical venue profile",
                "verbose_name_plural": "historical venue profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
