# Generated by Django 5.2.14 on 2026-07-20 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_historicalvenueprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvenueprofile",
            name="claim_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact for verifying a claim on this profile (not shown publicly)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="venueprofile",
            name="claim_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact for verifying a claim on this profile (not shown publicly)",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="venueprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The owner/primary manager of this venue",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venue_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
