# Generated by Django 5.2.14 on 2026-07-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0004_alter_venuesociallink_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvenueprofile",
            name="publish_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("published", "Published"),
                    ("suppressed", "Suppressed"),
                ],
                default="draft",
                help_text="Draft → Pending Review → Published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="venueprofile",
            name="publish_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Review"),
                    ("published", "Published"),
                    ("suppressed", "Suppressed"),
                ],
                default="draft",
                help_text="Draft → Pending Review → Published",
                max_length=20,
            ),
        ),
    ]
