# Generated by Django 6.0.3 on 2026-04-21 01:59

import django.db.models.deletion
import modelsearch.index
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for UI (e.g., lucide icon name)",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("website", models.URLField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, upload_to="profiles/%(class)s/"),
                ),
                (
                    "header_image",
                    models.ImageField(blank=True, upload_to="headers/%(class)s/"),
                ),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Draft → Pending Review → Published",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the profile was submitted for review",
                        null=True,
                    ),
                ),
                ("stripe_account_id", models.CharField(blank=True, max_length=255)),
                ("stripe_onboarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("band", "Band"),
                            ("collective", "Collective"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("bio", wagtail.fields.RichTextField(blank=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Current city/region", max_length=255
                    ),
                ),
                (
                    "home_region",
                    models.CharField(
                        blank=True, help_text="Origin/roots", max_length=255
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_profiles",
                        to="core.address",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_creator_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The owner/primary manager of this profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disciplines",
                    models.ManyToManyField(
                        blank=True, related_name="creators", to="creators.discipline"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional; most relevant for musicians.",
                        related_name="creators",
                        to="creators.genre",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name="CreatorSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("bandcamp", "Bandcamp"),
                            ("soundcloud", "SoundCloud"),
                            ("spotify", "Spotify"),
                            ("youtube", "YouTube"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("mastodon", "Mastodon"),
                            ("bluesky", "Bluesky"),
                            ("etsy", "Etsy"),
                            ("threads", "Threads"),
                            ("twitter_x", "X / Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="creators.creatorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "platform"],
            },
        ),
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("embed", "Embed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="creators/media/")),
                (
                    "embed_url",
                    models.URLField(
                        blank=True,
                        help_text="URL from SoundCloud, Bandcamp, YouTube, or Vimeo",
                    ),
                ),
                (
                    "embed_html",
                    models.TextField(blank=True, help_text="Cached oEmbed HTML"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="creators/thumbnails/"),
                ),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="creators.creatorprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="creators.discipline",
                    ),
                ),
            ],
            options={
                "ordering": ["discipline__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific skills across any discipline",
                related_name="creators",
                to="creators.skill",
            ),
        ),
        migrations.CreateModel(
            name="CreatorMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("left_date", models.DateField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The band or collective",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="creators.creatorprofile",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="The individual member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="creators.creatorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["sort_order", "member__display_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "member"), name="unique_membership"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("name", "discipline"), name="unique_skill_per_discipline"
            ),
        ),
    ]
