# Generated by Django 5.2.14 on 2026-05-14 03:36

import django.db.models.deletion
import simple_history.models
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_historicalreport_historicaluserprofile"),
        ("creators", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCreatorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("slug", models.SlugField(max_length=255)),
                ("website", models.URLField(blank=True)),
                ("profile_image", models.TextField(blank=True, max_length=100)),
                ("header_image", models.TextField(blank=True, max_length=100)),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        help_text="Draft → Pending Review → Published",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the profile was submitted for review",
                        null=True,
                    ),
                ),
                ("stripe_account_id", models.CharField(blank=True, max_length=255)),
                ("stripe_onboarded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("band", "Band"),
                            ("collective", "Collective"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("bio", wagtail.fields.RichTextField(blank=True)),
                (
                    "other_skills",
                    models.CharField(
                        blank=True,
                        help_text="Skills not in the list above (comma-separated)",
                        max_length=500,
                    ),
                ),
                (
                    "other_genres",
                    models.CharField(
                        blank=True,
                        help_text="Genres not in the list above (comma-separated)",
                        max_length=500,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Current city/region", max_length=255
                    ),
                ),
                (
                    "home_region",
                    models.CharField(
                        blank=True, help_text="Origin/roots", max_length=255
                    ),
                ),
                (
                    "booking_email",
                    models.EmailField(
                        blank=True,
                        help_text="Booking contact email (shown to venues on accepted bookings). Falls back to account email if blank.",
                        max_length=254,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.address",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The owner/primary manager of this profile",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical creator profile",
                "verbose_name_plural": "historical creator profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
