# Generated by Django 6.0.3 on 2026-05-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="booking_email",
            field=models.EmailField(
                blank=True,
                help_text="Booking contact email (shown to venues on accepted bookings). Falls back to account email if blank.",
                max_length=254,
            ),
        ),
    ]
