# Generated by Django 6.0.3 on 2026-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0002_creatorprofile_booking_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="other_genres",
            field=models.CharField(
                blank=True,
                help_text="Genres not in the list above (comma-separated)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="creatorprofile",
            name="other_skills",
            field=models.CharField(
                blank=True,
                help_text="Skills not in the list above (comma-separated)",
                max_length=500,
            ),
        ),
    ]
