# Generated by Django 5.2.14 on 2026-07-20 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0002_historicalcreatorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatormembership",
            name="guest_email",
            field=models.EmailField(
                blank=True,
                help_text="Optional — lets the row be claimed when they sign up",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="creatormembership",
            name="guest_name",
            field=models.CharField(
                blank=True, help_text="Member without a hub account", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="creatormembership",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="The individual member",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="creators.creatorprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatormembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("guest_name", ""), ("member__isnull", False)),
                    models.Q(
                        ("member__isnull", True),
                        models.Q(("guest_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="membership_member_xor_guest",
            ),
        ),
    ]
