# Generated by Django 5.2.14 on 2026-07-20 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0003_creatormembership_guest_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="claim_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact for verifying a claim on this profile (not shown publicly)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="historicalcreatorprofile",
            name="claim_contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Contact for verifying a claim on this profile (not shown publicly)",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="creatorprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The owner/primary manager of this profile",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
