# Generated by Django 5.2.14 on 2026-07-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0004_creatorprofile_claim_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorsociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("bandcamp", "Bandcamp"),
                    ("soundcloud", "SoundCloud"),
                    ("spotify", "Spotify"),
                    ("youtube", "YouTube"),
                    ("facebook", "Facebook"),
                    ("tiktok", "TikTok"),
                    ("mastodon", "Mastodon"),
                    ("bluesky", "Bluesky"),
                    ("etsy", "Etsy"),
                    ("threads", "Threads"),
                    ("twitter_x", "X / Twitter"),
                    ("linkedin", "LinkedIn"),
                    ("google_business", "Google Business"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
